version: "3"
services:
  app:
    build:
      context: .
      args:
        CI_JOB_USER: $CI_JOB_USER
        CI_JOB_TOKEN: $CI_JOB_TOKEN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
