name: Tagged releases

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/choopm/go-vue-jwt-grpc-greeter
          tag-semver: |
            {{major}}.{{minor}}.{{patch}}
          tag-latest: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: release
          build-args: |
            "GITHUB_TOKEN=${{ secrets.CR_PAT }}:x-oauth-basic"
          tags: ${{ steps.docker_meta.outputs.tags }}
